### ISSUE TITLE
ARAD-1K Dataset训练数据集的超链接好像有问题。

### ISSUE THREAD

**Issue by chengmohan** [bowenzhao-zju/PPIE-SSARN#1]
ARAD-1K Dataset训练数据集的超链接好像有问题。

**Comment by bowenzhao-zju** [comment]
已修正训练集链接，谢谢提醒！

**Comment by chengmohan** [comment]
好的的麻烦了。&nbsp;


程默涵
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月6日(星期六) 晚上10:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bowenzhao-zju/PPIE-SSARN] ARAD-1K Dataset训练数据集的超链接好像有问题。 (Issue #1)





 
已修正训练集链接，谢谢提醒！
