### ISSUE TITLE
DDFM

### ISSUE THREAD

**Issue by Matsuri247** [bowenzhao-zju/PPIE-SSARN#2]
What's the difference between the DDFM in your paper and the DDF module(CVPR 2021)? Are they identical? If so, how do you communicate with the reviewers as you treat DDFM as one of your contributions in the paper? Looking forward to your reply.

**Comment by bowenzhao-zju** [comment]
Thank you for acknowledging and recognizing our research work. This paper [45] indeed inspires DDMF. Based on the literature analysis, we observe that designing a particular initial feature extraction module for MSFA raw mosaic images is desirable, as it is sensitive to spatial and spectral variations to avoid artifacts and aliasing problems [40]. So, we introduce the idea of DDF into the MSFA demosaicing task to effectively extract preliminary features from the raw mosaic image. There are differences between the DDFM and DDF, such as the elements operation method and feature extraction in the channel branch. We also cite the paper of the DDF module in our paper. 
I hope the formal version codes and datasets can help you!
I am looking forward to communicating with you more!
